# Generated by Django 3.2.25 on 2025-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20250813_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('demande', 'Demande'), ('incident', 'Incident')], default='demande', max_length=20),
        ),
    ]
